apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assignment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 
  storageClassName: "assignment-storage-class"